'use client';

import { FormEvent } from 'react';
import { useTranslation } from '../../../lib/i18n-client';
import {
  PRIMARY_PRODUCT_CONTENT_LOCALE,
  type ProductContentLocale,
} from '@/constants/product-content-locales';
import type { AttributeLocaleTextMap } from '@/lib/admin/attribute-locale-helpers';
import { AttributeLocaleSwitcher } from './AttributeLocaleSwitcher';

interface CreateAttributeFormProps {
  contentLocale: ProductContentLocale;
  formNames: AttributeLocaleTextMap;
  isCreatingAttribute: boolean;
  onContentLocaleChange: (locale: ProductContentLocale) => void;
  onFormNameChange: (locale: ProductContentLocale, value: string) => void;
  onSubmit: (event: FormEvent) => void;
  onCancel: () => void;
}

export function CreateAttributeForm({
  contentLocale,
  formNames,
  isCreatingAttribute,
  onContentLocaleChange,
  onFormNameChange,
  onSubmit,
  onCancel,
}: CreateAttributeFormProps) {
  const { t } = useTranslation();

  return (
    <div className="mb-6 rounded-lg border border-gray-200 bg-white p-6 shadow-sm">
      <h2 className="mb-4 text-lg font-semibold text-gray-900">
        {t('admin.attributes.createNewAttribute')}
      </h2>
      <form onSubmit={onSubmit} className="space-y-4">
        <AttributeLocaleSwitcher value={contentLocale} onChange={onContentLocaleChange} />
        <div>
          <label className="mb-1 block text-sm font-medium text-gray-700">
            {t('admin.attributes.name')}{' '}
            <span className="text-red-500">{t('admin.attributes.required')}</span>
            {contentLocale === PRIMARY_PRODUCT_CONTENT_LOCALE ? (
              <span className="ml-1 text-xs text-gray-500">
                ({t('admin.attributes.primaryLocaleRequired')})
              </span>
            ) : null}
          </label>
          <input
            type="text"
            value={formNames[contentLocale]}
            onChange={(e) => onFormNameChange(contentLocale, e.target.value)}
            placeholder={t('admin.attributes.namePlaceholder')}
            className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:border-transparent focus:ring-2 focus:ring-gray-900"
          />
          <p className="mt-1 text-xs text-gray-500">{t('admin.attributes.keyAutoGenerated')}</p>
        </div>
        <div className="flex gap-3 pt-2">
          <button
            type="submit"
            disabled={isCreatingAttribute}
            className="rounded-lg bg-gray-900 px-4 py-2 text-white transition-colors hover:bg-gray-800 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {isCreatingAttribute
              ? t('admin.attributes.creating')
              : t('admin.attributes.createAttribute')}
          </button>
          <button
            type="button"
            onClick={onCancel}
            className="rounded-lg bg-gray-200 px-4 py-2 text-gray-700 transition-colors hover:bg-gray-300"
          >
            {t('admin.attributes.cancel')}
          </button>
        </div>
      </form>
    </div>
  );
}
