import {
  PROFILE_DESKTOP_ALERT_ERROR_CLASS,
  PROFILE_DESKTOP_ALERT_SUCCESS_CLASS,
  PROFILE_DESKTOP_CARD_CLASS,
  PROFILE_DESKTOP_DANGER_BUTTON_CLASS,
  PROFILE_DESKTOP_INPUT_CLASS,
  PROFILE_DESKTOP_OUTLINE_BUTTON_CLASS,
  PROFILE_DESKTOP_PRIMARY_BUTTON_CLASS,
  PROFILE_DESKTOP_SECTION_TITLE_CLASS,
} from './profile-desktop-page';

/** Clay corner radius — matches profile / site forms. */
export const ADMIN_UI_RADIUS_PX = 15;

export const ADMIN_UI_RADIUS_CLASS = '!rounded-[15px]';

export const ADMIN_INPUT_CLASS = PROFILE_DESKTOP_INPUT_CLASS;

export const ADMIN_CARD_CLASS = PROFILE_DESKTOP_CARD_CLASS;

export const ADMIN_PRIMARY_BUTTON_CLASS = PROFILE_DESKTOP_PRIMARY_BUTTON_CLASS;

export const ADMIN_OUTLINE_BUTTON_CLASS = PROFILE_DESKTOP_OUTLINE_BUTTON_CLASS;

export const ADMIN_DANGER_BUTTON_CLASS = PROFILE_DESKTOP_DANGER_BUTTON_CLASS;

export const ADMIN_SECTION_TITLE_CLASS = PROFILE_DESKTOP_SECTION_TITLE_CLASS;

export const ADMIN_ALERT_ERROR_CLASS = PROFILE_DESKTOP_ALERT_ERROR_CLASS;

export const ADMIN_ALERT_SUCCESS_CLASS = PROFILE_DESKTOP_ALERT_SUCCESS_CLASS;

/** Wrapper applied to all admin page content (see AdminLayoutClient). */
export const ADMIN_THEMED_CONTENT_CLASS = 'admin-themed-content';
