/** Shared delete confirmation modal — same motion as admin delete dialog. */
export {
  ADMIN_DELETE_MODAL_BACKDROP_IN_CLASS as CONFIRM_DELETE_MODAL_BACKDROP_IN_CLASS,
  ADMIN_DELETE_MODAL_BACKDROP_OUT_CLASS as CONFIRM_DELETE_MODAL_BACKDROP_OUT_CLASS,
  ADMIN_DELETE_MODAL_EXIT_FALLBACK_MS as CONFIRM_DELETE_MODAL_EXIT_FALLBACK_MS,
  ADMIN_DELETE_MODAL_PANEL_IN_CLASS as CONFIRM_DELETE_MODAL_PANEL_IN_CLASS,
  ADMIN_DELETE_MODAL_PANEL_OUT_ANIMATION_NAME as CONFIRM_DELETE_MODAL_PANEL_OUT_ANIMATION_NAME,
  ADMIN_DELETE_MODAL_PANEL_OUT_CLASS as CONFIRM_DELETE_MODAL_PANEL_OUT_CLASS,
  ADMIN_DELETE_MODAL_Z_INDEX as CONFIRM_DELETE_MODAL_Z_INDEX,
} from './admin-delete-modal';
