import {
  ABOUT_US_SECTION_MIN_HEIGHT_PX,
  ABOUT_US_SECTION_OFFSET_TOP_PX,
} from './about-us-section';
import {
  BEST_PRODUCTS_GRID_OFFSET_TOP_PX,
  BEST_PRODUCTS_HEADING_MIN_HEIGHT_PX,
  BEST_PRODUCTS_SECTION_OFFSET_TOP_PX,
  HOME_PRODUCT_CARD_HEIGHT_PX,
} from './home-sections';
import {
  FOOTER_HEIGHT_PX,
  FOOTER_PADDING_BOTTOM_PX,
  FOOTER_PADDING_TOP_PX,
  FOOTER_YELLOW_TOP_PX,
} from './footer';
import {
  SALE_BANNER_HEIGHT_PX,
  SALE_BANNER_OFFSET_TOP_PX,
  SALE_HEADING_MIN_HEIGHT_PX,
  SALE_SECTION_OFFSET_TOP_PX,
} from './sale-section';
import {
  WHY_US_GRID_OFFSET_TOP_PX,
  WHY_US_HEADING_MIN_HEIGHT_PX,
  WHY_US_IMAGE_BOX_HEIGHT_PX,
  WHY_US_LAYOUT_SCALE,
  WHY_US_SECTION_OFFSET_TOP_PX,
} from './why-us-section';

/** Prefetch below-the-fold blocks before they enter the viewport. */
export const LAZY_LOAD_ROOT_MARGIN_PX = 480;

/** Best products row skeleton — matches heading + card strip layout. */
export const HOME_BEST_PRODUCTS_PLACEHOLDER_MIN_HEIGHT_PX =
  BEST_PRODUCTS_SECTION_OFFSET_TOP_PX +
  BEST_PRODUCTS_HEADING_MIN_HEIGHT_PX +
  BEST_PRODUCTS_GRID_OFFSET_TOP_PX +
  HOME_PRODUCT_CARD_HEIGHT_PX +
  32;

export const HOME_SALE_SECTION_PLACEHOLDER_MIN_HEIGHT_PX =
  SALE_SECTION_OFFSET_TOP_PX +
  SALE_HEADING_MIN_HEIGHT_PX +
  SALE_BANNER_OFFSET_TOP_PX +
  SALE_BANNER_HEIGHT_PX;

const WHY_US_CARD_CONTENT_ESTIMATE_PX = Math.round(
  WHY_US_IMAGE_BOX_HEIGHT_PX + WHY_US_LAYOUT_SCALE * (23 + 48 + 72),
);

export const HOME_WHY_US_SECTION_PLACEHOLDER_MIN_HEIGHT_PX =
  WHY_US_SECTION_OFFSET_TOP_PX +
  WHY_US_HEADING_MIN_HEIGHT_PX +
  WHY_US_GRID_OFFSET_TOP_PX +
  WHY_US_CARD_CONTENT_ESTIMATE_PX;

export const HOME_ABOUT_US_SECTION_PLACEHOLDER_MIN_HEIGHT_PX =
  ABOUT_US_SECTION_OFFSET_TOP_PX + ABOUT_US_SECTION_MIN_HEIGHT_PX;

export const SITE_FOOTER_PLACEHOLDER_MIN_HEIGHT_PX =
  FOOTER_YELLOW_TOP_PX + FOOTER_PADDING_TOP_PX + FOOTER_HEIGHT_PX + FOOTER_PADDING_BOTTOM_PX;
