import { MOBILE_HOME_BG, MOBILE_HOME_BOTTOM_CONTENT_PADDING_PX, MOBILE_HOME_DESIGN_WIDTH_PX } from './mobile-home';
import {
  BEST_PRODUCTS_HEADING_COLOR,
  HOME_PRODUCT_CARD_ASSETS,
  HOME_PRODUCT_CARD_RATING_COLOR,
  HOME_PRODUCT_CARD_TEXT_DARK,
  HOME_PRODUCT_CARD_TEXT_MUTED,
} from './home-sections';

/** Figma `74:798` — mobile wishlist product card artboard width (px). */
export const MOBILE_WISHLIST_CARD_DESIGN_WIDTH_PX = 184;

/** Figma `74:798` — mobile wishlist product card height (px). */
export const MOBILE_WISHLIST_CARD_DESIGN_HEIGHT_PX = 330;

export const MOBILE_WISHLIST_PAGE_HORIZONTAL_PADDING_PX = 20;
/** Extra space below the fixed mobile header before the page title. */
export const MOBILE_WISHLIST_PAGE_PADDING_TOP_PX = 28;
export const MOBILE_WISHLIST_PAGE_PADDING_BOTTOM_PX = MOBILE_HOME_BOTTOM_CONTENT_PADDING_PX;
export const MOBILE_WISHLIST_PAGE_BG = MOBILE_HOME_BG;
export const MOBILE_WISHLIST_PAGE_TITLE_COLOR = BEST_PRODUCTS_HEADING_COLOR;
export const MOBILE_WISHLIST_TITLE_TO_GRID_GAP_PX = 16;

export const MOBILE_WISHLIST_GRID_COLUMNS = 2;
export const MOBILE_WISHLIST_CARD_COLUMN_GAP_PX = 10;
export const MOBILE_WISHLIST_CARD_ROW_GAP_PX = 10;

/** Two-up grid card width on the 375 design artboard. */
export const MOBILE_WISHLIST_CARD_WIDTH_PX = Math.floor(
  (MOBILE_HOME_DESIGN_WIDTH_PX
    - MOBILE_WISHLIST_PAGE_HORIZONTAL_PADDING_PX * 2
    - MOBILE_WISHLIST_CARD_COLUMN_GAP_PX)
  / MOBILE_WISHLIST_GRID_COLUMNS,
);

export const MOBILE_WISHLIST_CARD_HEIGHT_PX = Math.round(
  MOBILE_WISHLIST_CARD_WIDTH_PX
    * (MOBILE_WISHLIST_CARD_DESIGN_HEIGHT_PX / MOBILE_WISHLIST_CARD_DESIGN_WIDTH_PX),
);

export const MOBILE_WISHLIST_CARD_RADIUS_PX = 30;
export const MOBILE_WISHLIST_CARD_BG = '#ffffff';

export const MOBILE_WISHLIST_CARD_IMAGE_FRAME_HEIGHT_PX = 161;
export const MOBILE_WISHLIST_CARD_IMAGE_FRAME_WIDTH_PX = 200;
export const MOBILE_WISHLIST_CARD_IMAGE_FRAME_LEFT_PX = -10;
export const MOBILE_WISHLIST_CARD_IMAGE_FRAME_TOP_PX = 14;
export const MOBILE_WISHLIST_CARD_IMAGE_FRAME_RADIUS_PX = 25;
export const MOBILE_WISHLIST_CARD_IMAGE_INNER_WIDTH_PX = 174;
export const MOBILE_WISHLIST_CARD_IMAGE_INNER_HEIGHT_PX = 134;
export const MOBILE_WISHLIST_CARD_IMAGE_INNER_LEFT_PX = 13;
export const MOBILE_WISHLIST_CARD_IMAGE_INNER_TOP_PX = 26;

export const MOBILE_WISHLIST_CARD_HEART_WIDTH_PX = 30;
export const MOBILE_WISHLIST_CARD_HEART_HEIGHT_PX = 27;
export const MOBILE_WISHLIST_CARD_HEART_TOP_PX = 6;
export const MOBILE_WISHLIST_CARD_HEART_RIGHT_PX = 22;

export const MOBILE_WISHLIST_CARD_CONTENT_PADDING_X_PX = 8;
export const MOBILE_WISHLIST_CARD_CONTENT_TOP_PX = 182;
export const MOBILE_WISHLIST_CARD_TITLE_SIZE_PX = 16;
export const MOBILE_WISHLIST_CARD_TITLE_LINE_HEIGHT_PX = 28;
export const MOBILE_WISHLIST_CARD_SUBTITLE_SIZE_PX = 14;
export const MOBILE_WISHLIST_CARD_SUBTITLE_LINE_HEIGHT_PX = 28;
export const MOBILE_WISHLIST_CARD_PRICE_SIZE_PX = 18;
export const MOBILE_WISHLIST_CARD_PRICE_LINE_HEIGHT_PX = 24;
export const MOBILE_WISHLIST_CARD_COMPARE_SIZE_PX = 12;
export const MOBILE_WISHLIST_CARD_COMPARE_LINE_HEIGHT_PX = 24;
export const MOBILE_WISHLIST_CARD_COMPARE_COLOR = '#4d4d4d';
export const MOBILE_WISHLIST_CARD_PRICE_COLOR = '#000000';
export const MOBILE_WISHLIST_CARD_TEXT_DARK = HOME_PRODUCT_CARD_TEXT_DARK;
export const MOBILE_WISHLIST_CARD_TEXT_MUTED = HOME_PRODUCT_CARD_TEXT_MUTED;
export const MOBILE_WISHLIST_CARD_RATING_COLOR = HOME_PRODUCT_CARD_RATING_COLOR;
export const MOBILE_WISHLIST_CARD_RATING_SIZE_PX = 13.745;
export const MOBILE_WISHLIST_CARD_RATING_LINE_HEIGHT_PX = 20;
export const MOBILE_WISHLIST_CARD_RATING_STAR_SIZE_PX = 14;
export const MOBILE_WISHLIST_CARD_RATING_STAR_TEXT_GAP_PX = 3;

export const MOBILE_WISHLIST_CARD_CTA_TOP_PX = 272;
export const MOBILE_WISHLIST_CARD_CTA_HORIZONTAL_INSET_PX = 5;
export const MOBILE_WISHLIST_CARD_CTA_HEIGHT_PX = 50;
export const MOBILE_WISHLIST_CARD_CTA_PADDING_LEFT_PX = 20;
export const MOBILE_WISHLIST_CARD_CTA_PADDING_RIGHT_PX = 9;
export const MOBILE_WISHLIST_CARD_CTA_FONT_SIZE_PX = 14;
export const MOBILE_WISHLIST_CARD_CTA_LINE_HEIGHT_PX = 21;
export const MOBILE_WISHLIST_CARD_CTA_ICON_SIZE_PX = 40;
export const MOBILE_WISHLIST_CARD_CTA_CART_ICON_SIZE_PX = 20;

export const MOBILE_WISHLIST_CARD_ASSETS = {
  star: HOME_PRODUCT_CARD_ASSETS.star,
  cart: HOME_PRODUCT_CARD_ASSETS.cart,
  placeholderImage: HOME_PRODUCT_CARD_ASSETS.placeholderImage,
} as const;
