import {
  BEST_PRODUCTS_HEADING_COLOR,
  HOME_PRODUCT_CARD_ASSETS,
  HOME_PRODUCT_CARD_RATING_COLOR,
  HOME_PRODUCT_CARD_SWATCH_GAP_PX,
  HOME_PRODUCT_CARD_SWATCH_SIZE_PX,
  HOME_PRODUCT_CARD_TEXT_DARK,
  HOME_PRODUCT_CARD_TEXT_MUTED,
} from './home-sections';
import { MOBILE_HOME_DESIGN_WIDTH_PX, MOBILE_HOME_HORIZONTAL_PADDING_PX, MOBILE_HOME_TABLET_GRID_COLUMNS, MOBILE_HOME_TABLET_MIN_VIEWPORT_PX } from './mobile-home';
import {
  HOME_SECTION_PADDING_LEFT_PX,
  HOME_SECTION_PADDING_RIGHT_PX,
} from './home-sections';
import {
  PRODUCTS_CATALOG_MOBILE_HEADER_ALIGN_OFFSET_RIGHT_PX,
  PRODUCTS_CATALOG_MOBILE_TITLE_ALIGN_OFFSET_X_PX,
} from './products-catalog';

/** Matches mobile navbar / wishlist horizontal inset (`74:729`). */
export const MOBILE_PRODUCTS_CATALOG_PAGE_HORIZONTAL_PADDING_PX = MOBILE_HOME_HORIZONTAL_PADDING_PX;

/** Negates `HomeContentHorizontalFrame` padding to reach viewport edges. */
export const MOBILE_PRODUCTS_CATALOG_FRAME_BREAKOUT_LEFT_PX = HOME_SECTION_PADDING_LEFT_PX;
export const MOBILE_PRODUCTS_CATALOG_FRAME_BREAKOUT_RIGHT_PX = HOME_SECTION_PADDING_RIGHT_PX;

/** Navbar-aligned content width on the 375 artboard (375 − 40). */
export const MOBILE_PRODUCTS_CATALOG_GRID_TRACK_WIDTH_PX =
  MOBILE_HOME_DESIGN_WIDTH_PX - MOBILE_PRODUCTS_CATALOG_PAGE_HORIZONTAL_PADDING_PX * 2;

export const MOBILE_PRODUCTS_CATALOG_GRID_COLUMNS = 2;
export const MOBILE_PRODUCTS_CATALOG_TABLET_GRID_COLUMNS = MOBILE_HOME_TABLET_GRID_COLUMNS;
export const MOBILE_PRODUCTS_CATALOG_CARD_COLUMN_GAP_PX = 14;
export const MOBILE_PRODUCTS_CATALOG_CARD_ROW_GAP_PX = 18;

/** Space below mobile filter/sort row before the first card row. */
export const MOBILE_PRODUCTS_CATALOG_GRID_OFFSET_TOP_PX = 24;
/** Space between mobile page title and filter/sort toolbar. */
export const MOBILE_PRODUCTS_CATALOG_TITLE_TO_FILTERS_GAP_PX = 20;
/** @deprecated Use `MobileProductsCatalogTrack` — kept for title/header offset parity checks. */
export const MOBILE_PRODUCTS_CATALOG_GRID_ALIGN_OFFSET_X_PX =
  PRODUCTS_CATALOG_MOBILE_TITLE_ALIGN_OFFSET_X_PX;
/** @deprecated Use `MobileProductsCatalogTrack`. */
export const MOBILE_PRODUCTS_CATALOG_GRID_ALIGN_OFFSET_RIGHT_PX =
  PRODUCTS_CATALOG_MOBILE_HEADER_ALIGN_OFFSET_RIGHT_PX;

/** Two-up card width on the navbar-aligned 335px track. */
export const MOBILE_PRODUCTS_CATALOG_CARD_WIDTH_PX = Math.floor(
  (MOBILE_PRODUCTS_CATALOG_GRID_TRACK_WIDTH_PX - MOBILE_PRODUCTS_CATALOG_CARD_COLUMN_GAP_PX)
  / MOBILE_PRODUCTS_CATALOG_GRID_COLUMNS,
);

/** Figma `167:618` — mobile catalog product card artboard width (px). */
export const MOBILE_PRODUCTS_CATALOG_CARD_DESIGN_WIDTH_PX = 184;

/** Figma `167:618` — mobile catalog product card height (px); +7 for rating→CTA gap. */
export const MOBILE_PRODUCTS_CATALOG_CARD_DESIGN_HEIGHT_PX = 337;

export const MOBILE_PRODUCTS_CATALOG_CARD_HEIGHT_PX = Math.round(
  MOBILE_PRODUCTS_CATALOG_CARD_WIDTH_PX
    * (MOBILE_PRODUCTS_CATALOG_CARD_DESIGN_HEIGHT_PX / MOBILE_PRODUCTS_CATALOG_CARD_DESIGN_WIDTH_PX),
);

/** iPad mini — three-up grid card width for layout estimates. */
const MOBILE_PRODUCTS_CATALOG_TABLET_GRID_TRACK_WIDTH_PX =
  MOBILE_HOME_TABLET_MIN_VIEWPORT_PX - MOBILE_PRODUCTS_CATALOG_PAGE_HORIZONTAL_PADDING_PX * 2;

export const MOBILE_PRODUCTS_CATALOG_TABLET_CARD_WIDTH_PX = Math.floor(
  (MOBILE_PRODUCTS_CATALOG_TABLET_GRID_TRACK_WIDTH_PX
    - MOBILE_PRODUCTS_CATALOG_CARD_COLUMN_GAP_PX * (MOBILE_PRODUCTS_CATALOG_TABLET_GRID_COLUMNS - 1))
  / MOBILE_PRODUCTS_CATALOG_TABLET_GRID_COLUMNS,
);

export const MOBILE_PRODUCTS_CATALOG_TABLET_CARD_HEIGHT_PX = Math.round(
  MOBILE_PRODUCTS_CATALOG_TABLET_CARD_WIDTH_PX
    * (MOBILE_PRODUCTS_CATALOG_CARD_DESIGN_HEIGHT_PX / MOBILE_PRODUCTS_CATALOG_CARD_DESIGN_WIDTH_PX),
);

export const MOBILE_PRODUCTS_CATALOG_CARD_RADIUS_PX = 30;
export const MOBILE_PRODUCTS_CATALOG_CARD_BG = '#ffffff';

export const MOBILE_PRODUCTS_CATALOG_CARD_IMAGE_FRAME_HEIGHT_PX = 167;
export const MOBILE_PRODUCTS_CATALOG_CARD_IMAGE_FRAME_WIDTH_PX = 200;
export const MOBILE_PRODUCTS_CATALOG_CARD_IMAGE_FRAME_LEFT_PX = -10;
export const MOBILE_PRODUCTS_CATALOG_CARD_IMAGE_FRAME_TOP_PX = 8;
export const MOBILE_PRODUCTS_CATALOG_CARD_IMAGE_FRAME_RADIUS_PX = 25;
export const MOBILE_PRODUCTS_CATALOG_CARD_IMAGE_INNER_WIDTH_PX = 174;
export const MOBILE_PRODUCTS_CATALOG_CARD_IMAGE_INNER_HEIGHT_PX = 134;
export const MOBILE_PRODUCTS_CATALOG_CARD_IMAGE_INNER_LEFT_PX = 13;
export const MOBILE_PRODUCTS_CATALOG_CARD_IMAGE_INNER_TOP_PX = 19;

export const MOBILE_PRODUCTS_CATALOG_CARD_HEART_WIDTH_PX = 30;
export const MOBILE_PRODUCTS_CATALOG_CARD_HEART_HEIGHT_PX = 27;
export const MOBILE_PRODUCTS_CATALOG_CARD_HEART_TOP_PX = 6;
export const MOBILE_PRODUCTS_CATALOG_CARD_HEART_RIGHT_PX = 22;

export const MOBILE_PRODUCTS_CATALOG_CARD_CONTENT_PADDING_X_PX = 9;
export const MOBILE_PRODUCTS_CATALOG_CARD_CONTENT_TOP_PX = 165;
export const MOBILE_PRODUCTS_CATALOG_CARD_TITLE_SIZE_PX = 16;
export const MOBILE_PRODUCTS_CATALOG_CARD_TITLE_LINE_HEIGHT_PX = 28;
export const MOBILE_PRODUCTS_CATALOG_CARD_SUBTITLE_SIZE_PX = 14;
export const MOBILE_PRODUCTS_CATALOG_CARD_SUBTITLE_LINE_HEIGHT_PX = 28;
export const MOBILE_PRODUCTS_CATALOG_CARD_PRICE_SIZE_PX = 18;
export const MOBILE_PRODUCTS_CATALOG_CARD_PRICE_LINE_HEIGHT_PX = 24;
export const MOBILE_PRODUCTS_CATALOG_CARD_COMPARE_SIZE_PX = 12;
export const MOBILE_PRODUCTS_CATALOG_CARD_COMPARE_LINE_HEIGHT_PX = 24;
export const MOBILE_PRODUCTS_CATALOG_CARD_COMPARE_COLOR = '#4d4d4d';
export const MOBILE_PRODUCTS_CATALOG_CARD_PRICE_COLOR = '#000000';
export const MOBILE_PRODUCTS_CATALOG_CARD_TEXT_DARK = HOME_PRODUCT_CARD_TEXT_DARK;
export const MOBILE_PRODUCTS_CATALOG_CARD_TEXT_MUTED = HOME_PRODUCT_CARD_TEXT_MUTED;
export const MOBILE_PRODUCTS_CATALOG_CARD_RATING_COLOR = HOME_PRODUCT_CARD_RATING_COLOR;
export const MOBILE_PRODUCTS_CATALOG_CARD_RATING_SIZE_PX = 13.745;
export const MOBILE_PRODUCTS_CATALOG_CARD_RATING_LINE_HEIGHT_PX = 20;
export const MOBILE_PRODUCTS_CATALOG_CARD_RATING_STAR_SIZE_PX = 14;
export const MOBILE_PRODUCTS_CATALOG_CARD_RATING_STAR_TEXT_GAP_PX = 3;
/** Figma `167:627` — rating row top (px). */
export const MOBILE_PRODUCTS_CATALOG_CARD_RATING_TOP_PX = 247;
/** Space between rating row and add-to-cart CTA (Figma default ≈5px). */
export const MOBILE_PRODUCTS_CATALOG_CARD_RATING_TO_CTA_GAP_PX = 12;

export const MOBILE_PRODUCTS_CATALOG_CARD_SWATCH_SIZE_PX = HOME_PRODUCT_CARD_SWATCH_SIZE_PX;
export const MOBILE_PRODUCTS_CATALOG_CARD_SWATCH_GAP_PX = HOME_PRODUCT_CARD_SWATCH_GAP_PX;
export const MOBILE_PRODUCTS_CATALOG_CARD_SWATCH_MAX_VISIBLE = 4;
export const MOBILE_PRODUCTS_CATALOG_CARD_SWATCH_SELECTED_BORDER_COLOR = HOME_PRODUCT_CARD_TEXT_DARK;
/** Gap between subtitle row and color swatches (Figma `167:642` y=217). */
export const MOBILE_PRODUCTS_CATALOG_CARD_SWATCHES_MARGIN_TOP_PX = 0;

export const MOBILE_PRODUCTS_CATALOG_CARD_CTA_TOP_PX =
  MOBILE_PRODUCTS_CATALOG_CARD_RATING_TOP_PX
  + MOBILE_PRODUCTS_CATALOG_CARD_RATING_LINE_HEIGHT_PX
  + MOBILE_PRODUCTS_CATALOG_CARD_RATING_TO_CTA_GAP_PX;
export const MOBILE_PRODUCTS_CATALOG_CARD_CTA_HORIZONTAL_INSET_PX = 5;
export const MOBILE_PRODUCTS_CATALOG_CARD_CTA_HEIGHT_PX = 50;
export const MOBILE_PRODUCTS_CATALOG_CARD_CTA_PADDING_LEFT_PX = 20;
export const MOBILE_PRODUCTS_CATALOG_CARD_CTA_PADDING_RIGHT_PX = 9;
export const MOBILE_PRODUCTS_CATALOG_CARD_CTA_FONT_SIZE_PX = 14;
export const MOBILE_PRODUCTS_CATALOG_CARD_CTA_LINE_HEIGHT_PX = 21;
export const MOBILE_PRODUCTS_CATALOG_CARD_CTA_ICON_SIZE_PX = 40;
export const MOBILE_PRODUCTS_CATALOG_CARD_CTA_CART_ICON_SIZE_PX = 20;

/** Mobile catalog page title — pink section style. */
export const MOBILE_PRODUCTS_CATALOG_TITLE_COLOR = BEST_PRODUCTS_HEADING_COLOR;

export const MOBILE_PRODUCTS_CATALOG_CARD_ASSETS = {
  star: HOME_PRODUCT_CARD_ASSETS.star,
  cart: '/assets/mobile-bottom-nav/icon-cart.svg',
  placeholderImage: HOME_PRODUCT_CARD_ASSETS.placeholderImage,
} as const;
