import { BRAND_COLORS } from './brand';
import {
  HEADER_CONTENT_CLEARANCE_DESKTOP_PX,
  HEADER_CONTENT_CLEARANCE_MOBILE_PX,
} from './header';
import {
  HOME_PRODUCT_CARD_DESIGN_HEIGHT_PX,
  HOME_PRODUCT_CARD_DESIGN_WIDTH_PX,
  HOME_SECTION_CONTENT_MAX_WIDTH_PX,
  HOME_SECTION_PADDING_LEFT_PX,
  HOME_SECTION_PADDING_RIGHT_PX,
} from './home-sections';

/** Figma shop page — catalog layout tokens. */
export const PRODUCTS_CATALOG_MAX_WIDTH_PX = HOME_SECTION_CONTENT_MAX_WIDTH_PX;
export const PRODUCTS_CATALOG_PADDING_LEFT_PX = HOME_SECTION_PADDING_LEFT_PX;
export const PRODUCTS_CATALOG_PADDING_RIGHT_PX = HOME_SECTION_PADDING_RIGHT_PX;

/** Top inset — content clears fixed navbar (same pattern as home hero under transparent bar). */
export const PRODUCTS_CATALOG_OFFSET_TOP_MOBILE_PX = HEADER_CONTENT_CLEARANCE_MOBILE_PX;
export const PRODUCTS_CATALOG_OFFSET_TOP_DESKTOP_PX = HEADER_CONTENT_CLEARANCE_DESKTOP_PX;

export const PRODUCTS_CATALOG_SIDEBAR_WIDTH_PX = 281;
export const PRODUCTS_CATALOG_MAIN_GAP_PX = 52;

export const PRODUCTS_CATALOG_CARD_GAP_PX = 12;
export const PRODUCTS_CATALOG_CARD_COLUMNS = 3;
export const PRODUCTS_CATALOG_CARD_WIDTH_PX = 344;

export const PRODUCTS_CATALOG_CARD_HEIGHT_PX = Math.round(
  PRODUCTS_CATALOG_CARD_WIDTH_PX *
    (HOME_PRODUCT_CARD_DESIGN_HEIGHT_PX / HOME_PRODUCT_CARD_DESIGN_WIDTH_PX),
);

export const PRODUCTS_CATALOG_CARD_LAYOUT_SCALE =
  PRODUCTS_CATALOG_CARD_WIDTH_PX / HOME_PRODUCT_CARD_DESIGN_WIDTH_PX;

export const PRODUCTS_CATALOG_FILTER_SECTION_BG = '#f6f6f6';
export const PRODUCTS_CATALOG_FILTER_SECTION_RADIUS_PX = 16;
export const PRODUCTS_CATALOG_FILTER_SECTION_SHADOW = '0px 1px 4px rgba(0, 0, 0, 0.06)';
export const PRODUCTS_CATALOG_FILTER_TITLE_LETTER_SPACING_PX = 1.4;
export const PRODUCTS_CATALOG_FILTER_TITLE_SIZE_PX = 11;
export const PRODUCTS_CATALOG_FILTER_ACCENT = '#5281e1';
export const PRODUCTS_CATALOG_BREADCRUMB_MUTED = 'rgba(29, 28, 22, 0.36)';
export const PRODUCTS_CATALOG_TEXT_DARK = '#1d1c16';

export const PRODUCTS_CATALOG_SORT_PILL_BG = BRAND_COLORS.pink;
export const PRODUCTS_CATALOG_VIEW_PILL_BG = '#f3f3f3';
export const PRODUCTS_CATALOG_PILL_HEIGHT_PX = 48;
export const PRODUCTS_CATALOG_PILL_RADIUS_PX = 30;

export const PRODUCTS_CATALOG_CTA_WIDTH_PX = 200;
export const PRODUCTS_CATALOG_CTA_HEIGHT_PX = 56;
export const PRODUCTS_CATALOG_CTA_BG = BRAND_COLORS.pink;
export const PRODUCTS_CATALOG_CTA_INSET_SHADOW =
  'inset 0px -4px 8px rgba(0, 0, 0, 0.27), inset 0px 4px 4px rgba(255, 255, 255, 0.4), inset 0px 20px 40px -10px rgba(164, 60, 18, 0.2)';

export const PRODUCTS_CATALOG_FILTER_CHEVRON_SRC = '/assets/brand/icon-chevron.svg';
