import {
  HOME_SECTION_CHEVRON_SIZE_PX,
  HOME_SECTION_CONTENT_MAX_WIDTH_PX,
  HOME_SECTION_LINK_FONT_SIZE_PX,
  HOME_SECTION_LINK_GAP_PX,
  HOME_SECTION_LINK_LINE_HEIGHT_PX,
  HOME_SECTION_MAX_WIDTH_PX,
  HOME_SECTION_PADDING_LEFT_PX,
  HOME_SECTION_PADDING_RIGHT_PX,
  HOME_SECTION_STACK_GAP_PX,
} from './home-sections';

/** Figma node `51:357` — «Զեղչ» sale section heading. */
export const SALE_SECTION_MAX_WIDTH_PX = HOME_SECTION_MAX_WIDTH_PX;

/** Matches hero → best products spacing. */
export const SALE_SECTION_OFFSET_TOP_PX = HOME_SECTION_STACK_GAP_PX;

export const SALE_SECTION_PADDING_LEFT_PX = HOME_SECTION_PADDING_LEFT_PX;
export const SALE_SECTION_PADDING_RIGHT_PX = HOME_SECTION_PADDING_RIGHT_PX;
export const SALE_HEADING_PADDING_Y_PX = 7;
export const SALE_HEADING_MIN_HEIGHT_PX = 94;

export const SALE_TITLE_FONT_SIZE_PX = 50;
export const SALE_TITLE_LINE_HEIGHT_PX = 80;

export const SALE_HEADING_COLOR = '#ef95aa';

export const SALE_LINK_FONT_SIZE_PX = HOME_SECTION_LINK_FONT_SIZE_PX;
export const SALE_LINK_LINE_HEIGHT_PX = HOME_SECTION_LINK_LINE_HEIGHT_PX;
export const SALE_LINK_GAP_PX = HOME_SECTION_LINK_GAP_PX;
export const SALE_CHEVRON_SIZE_PX = HOME_SECTION_CHEVRON_SIZE_PX;

export const SALE_SECTION_ASSETS = {
  chevronRight: '/assets/home/icon-chevron-right-pink.svg',
  bannerDecoration: '/assets/home/sale-banner-decoration.png',
  bannerChild: '/assets/home/sale-banner-child.png',
} as const;

/** Figma node `51:363` — promo banner. */
/** Figma `51:363` y=1730 vs section `51:356` bottom y=1673. */
export const SALE_BANNER_OFFSET_TOP_PX = 57;
export const SALE_BANNER_HEIGHT_PX = 391;
export const SALE_BANNER_MAX_WIDTH_PX = HOME_SECTION_CONTENT_MAX_WIDTH_PX;
export const SALE_BANNER_RADIUS_PX = 30;
export const SALE_BANNER_BG = '#ef95aa';

export const SALE_BANNER_CONTENT_LEFT_PX = 57;
export const SALE_BANNER_CONTENT_WIDTH_PX = 512;
export const SALE_BANNER_TITLE_SUBTITLE_GAP_PX = 28;
export const SALE_BANNER_SUBTITLE_GAP_PX = 16;

export const SALE_BANNER_TITLE_SIZE_PX = 56;
export const SALE_BANNER_TITLE_LINE_HEIGHT_PX = 61;
export const SALE_BANNER_TITLE_SIZE_HY_PX = 44;
export const SALE_BANNER_TITLE_LINE_HEIGHT_HY_PX = 49;

export const SALE_BANNER_SUBTITLE_SIZE_PX = 16;
export const SALE_BANNER_SUBTITLE_LINE_HEIGHT_PX = 24;
export const SALE_BANNER_SUBTITLE_SIZE_HY_PX = 14;
export const SALE_BANNER_SUBTITLE_LINE_HEIGHT_HY_PX = 21;
export const SALE_BANNER_SUBTITLE_MAX_WIDTH_PX = SALE_BANNER_CONTENT_WIDTH_PX;

export const SALE_BANNER_CTA_WIDTH_PX = 243;
export const SALE_BANNER_CTA_HEIGHT_PX = 60;
export const SALE_BANNER_CTA_TEXT_SIZE_PX = 18;
export const SALE_BANNER_CTA_TEXT_LINE_HEIGHT_PX = 28;
export const SALE_BANNER_CTA_TEXT_COLOR = '#ff7f50';
export const SALE_BANNER_CTA_INSET_SHADOW =
  'inset 0px -4px 8px 0px rgba(0,0,0,0.1), inset 0px 4px 4px 0px rgba(255,255,255,0.4), inset 0px 20px 40px 0px rgba(164,60,18,0.2)';

/** Figma `51:364` — rotated decoration behind copy. */
export const SALE_BANNER_DECORATION_LEFT_PX = 215;
export const SALE_BANNER_DECORATION_TOP_PX = -112;
export const SALE_BANNER_DECORATION_WRAPPER_WIDTH_PX = 924.403;
export const SALE_BANNER_DECORATION_WRAPPER_HEIGHT_PX = 615.326;
export const SALE_BANNER_DECORATION_INNER_WIDTH_PX = 849;
export const SALE_BANNER_DECORATION_INNER_HEIGHT_PX = 386;
export const SALE_BANNER_DECORATION_INNER_WIDTH_RATIO =
  SALE_BANNER_DECORATION_INNER_WIDTH_PX / SALE_BANNER_DECORATION_WRAPPER_WIDTH_PX;
export const SALE_BANNER_DECORATION_INNER_HEIGHT_RATIO =
  SALE_BANNER_DECORATION_INNER_HEIGHT_PX / SALE_BANNER_DECORATION_WRAPPER_HEIGHT_PX;
export const SALE_BANNER_DECORATION_ROTATE_DEG = 16.83;
export const SALE_BANNER_DECORATION_Z_INDEX = 1;
export const SALE_BANNER_DECORATION_IMAGE_HEIGHT_PERCENT = 183.09;
export const SALE_BANNER_DECORATION_IMAGE_WIDTH_PERCENT = 105.15;
export const SALE_BANNER_DECORATION_IMAGE_LEFT_PERCENT = -5.15;
export const SALE_BANNER_DECORATION_IMAGE_TOP_PERCENT = -36.78;

/** Figma `51:370` — child photo on the right. */
export const SALE_BANNER_CHILD_LEFT_PX = 703;
export const SALE_BANNER_CHILD_TOP_PX = 2;
export const SALE_BANNER_CHILD_WIDTH_PX = 628;
export const SALE_BANNER_CHILD_HEIGHT_PX = 649;
export const SALE_BANNER_CHILD_RADIUS_PX = 7;
export const SALE_BANNER_CHILD_Z_INDEX = 2;
export const SALE_BANNER_CHILD_IMAGE_HEIGHT_PERCENT = 145.31;
export const SALE_BANNER_CHILD_IMAGE_LEFT_PERCENT = 5.14;
export const SALE_BANNER_CHILD_IMAGE_TOP_PERCENT = -35.8;
